substitutions:
  updates: 3s
  name: person_detection

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.6   #2.0.5
    platform_version: 5.3.0 #5.2.0
 
esphome:
  name: ${name}    

# external_components:
#   - source: my_components
#     components: [sen21231]
#     refresh: 0s 

external_components:
  
  - source: github://SeByDocKy/ESPhome/
    components: [ sen21231 ]
    refresh: 0s

logger:
  #level: very_verbose
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Person Fallback Hotspot"
    password: "sebydocky"   

i2c:
- sda: GPIO22
  scl: GPIO21
  id: i2c_bus
  scan: true

sensor:
  - platform: sen21231
    id: ${name}_person
    nfaces:
      name: ${name}_nfaces

    ###### First face detected #####  
    
    conf0:
      name: ${name}_conf0
    x0:
      name: ${name}_x0 
    y0:
      name: ${name}_y0
    w0:
      name: ${name}_w0
    h0:
      name: ${name}_h0          
    update_interval: ${updates}
    address: 0x62