substitutions:
  updates: 5s
  name: pmwc3

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.6   #2.0.5
    platform_version: 5.3.0 #5.2.0
 
esphome:
  name: ${name}
  
  
  
  # on_boot:
  #   priority: -100
  #   then:

  #     ######### Uncomment the next lamnda section to change I2C address, then replace the new I2C address in the sensor part ########

  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->set_i2c_address(0x65);

  #     #########  Uncomment the next lamnda section to perform the air/dry soil calibration   ##########
      
  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->set_air_calibration();

  #     #########  Uncomment the next lamnda section to perform the water/humid soil calibration   ##########
      
  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->set_water_calibration();
          

# external_components:
#   - source: my_components
#     components: [ pmwcs3]
#     refresh: 0s 


external_components:
  - source: github://SeByDocKy/ESPhome/
    components: [ pmwcs3]
    refresh: 0s

logger:
  #level: verbose
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pmwcs3 Fallback Hotspot"
    password: "sebydocky"   

i2c:
- sda: GPIO22
  scl: GPIO21
  id: i2c_bus
  scan: true

sensor:
  - platform: pmwcs3
    id: ${name}_pmwc3
    e25:
      name: ${name}_e25    
    ec:
      name: ${name}_ec
    temperature:
      name: ${name}_temperature 
    vwc:
      name: ${name}_vwc
