substitutions:
  name: velm6075
  updates: 10s
  
esphome:
  name: ${name}
  
external_components:
  # - source: my_components
  #   components: [veml6075]
  #   refresh: 0s
  - source: github://SeByDocKy/ESPhome/
    components: [ veml6075 ]
    refresh: 0s   


esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.6   #2.0.5
    platform_version: 5.3.0 #5.2.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: "SpeiBIIsSF4QxA3RlIzSmtC9YfvkjpC2hXWxOV+ehGA="

ota:
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Veml6075 Fallback Hotspot"
    password: "tV67NUGqWEtn"


i2c:
- sda: GPIO22
  scl: GPIO21
  id: i2c_bus
  scan: true


sensor: 
  - platform: veml6075
    update_interval: ${updates}
    #id: ${name}_1
    uva:
      name: ${name}_uva
    uvb:
      name: ${name}_uvb
    uvindex:
      name: ${name}_uvindex 
    visible_comp:
      name: ${name}_visible_comp
    ir_comp:
      name: ${name}_ir_comp
    rawuva:
      name: ${name}_rawuva
    rawuvb:
      name: ${name}_rawuvb
    dynamic: 'normal'  # 'normal'/'high'
    integration_time: '100ms' #'50ms'/'100ms'/'200ms'/'400ms'/'800ms'
    auto_force: 'disable' # 'disable' or 'one_or_uv'
    trigger: 'disable'  # 'disable' or 'one_or_uv'
    address: 0x10
  
 